# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  outputFolder: './_output'
  artifactsFolder: './_artifacts'
  testsFolder: './_tests'
  majorVersion: '0.1.10'
  minorVersion: $[counter('minorVersion', 1)]
  prowlarrVersion: '$(majorVersion).$(minorVersion)'
  buildName: '$(Build.SourceBranchName).$(prowlarrVersion)'
  sentryOrg: 'servarr'
  sentryUrl: 'https://sentry.servarr.com'
  dotnetVersion: '6.0.100'
  yarnCacheFolder: $(Pipeline.Workspace)/.yarn

trigger:
  branches:
    include:
    - develop
    - master

pr:
  branches:
    include:
    - develop
  paths:
    exclude:
    - src/NzbDrone.Core/Localization/Core
    - src/Prowlarr.API.*/openapi.json

stages:
  - stage: Analyze
    displayName: Analyze

    jobs:
    - job: Api_Docs
      displayName: API Docs
      condition: |
        and
        (
          succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop')
        )

      pool:
        vmImage: windows-2019

      steps:
      - checkout: self
        submodules: true
        persistCredentials: true
        fetchDepth: 1
      - bash: |
          git config --global user.email "development@lidarr.audio"
          git config --global user.name "Servarr"
          git checkout -b api-docs
          git add .
          curl -X POST -H "Authorization: token ${GITHUBTOKEN}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/prowlarr/prowlarr/pulls -d '{"head":"api-docs","base":"develop","title":"Update API docs"}'
        displayName: Commit API Doc Change
        continueOnError: true
        env:
          GITHUBTOKEN: $(githubToken)
